"""Provider protocol interfaces. Wire Shopify/Razorpay/ERP/3PL adapters
behind these contracts so the engine never depends on provider schemas."""
from __future__ import annotations

from typing import Protocol


class PaymentProvider(Protocol):
    def create_payment_link(self, negotiation_id: str, amount: float) -> dict: ...
    def fetch_payment(self, payment_id: str) -> dict: ...
    def verify_webhook(self, payload: bytes, signature: str) -> bool: ...


class CommerceProvider(Protocol):
    def fetch_product(self, sku: str) -> dict: ...
    def fetch_order(self, order_id: str) -> dict: ...


class InventoryProvider(Protocol):
    def fetch_inventory(self, product_id: str) -> dict: ...


class LogisticsProvider(Protocol):
    def create_shipment(self, offer: dict) -> dict: ...
    def track_shipment(self, tracking_id: str) -> dict: ...
